const db=window.supabase.createClient(ICA_CONFIG.supabaseUrl,ICA_CONFIG.supabaseKey);
const $=id=>document.getElementById(id); let issuers=[],types=[],details=[],credentials=[];
const val=id=>$(id).value.trim(); const show=(id,on)=>$(id).classList.toggle('hidden',!on);

async function consumeGmsHandoff(){
  const raw=location.hash||'';
  const m=raw.match(/^#gms_sso=([A-Za-z0-9_-]+)$/);
  if(!m)return false;
  history.replaceState({},document.title,location.pathname+location.search);
  $('loginMsg').textContent='GMS 관리자 인증을 확인하는 중…';
  const {data,error}=await db.auth.verifyOtp({token_hash:m[1],type:'magiclink'});
  if(error||!data?.session){$('loginMsg').textContent='GMS 인증 연결이 만료되었거나 유효하지 않습니다.';return false}
  await enter(data.session);return true;
}
async function init(){
  if(await consumeGmsHandoff())return;
  const {data:{session}}=await db.auth.getSession();
  if(session) await enter(session); else show('loginView',true);
}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='확인 중…';const {data,error}=await db.auth.signInWithPassword({email:val('email'),password:val('password')});if(error){$('loginMsg').textContent='로그인 실패: '+error.message;return}await enter(data.session)});
$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
async function enter(session){const {data:ctx,error}=await db.rpc('gms_get_my_admin_context');if(error||!ctx?.is_admin){await db.auth.signOut();$('loginMsg').textContent='ICA 관리자 권한이 없습니다.';show('loginView',true);return}$('adminEmail').textContent=ctx.email+' · '+ctx.role;show('logoutBtn',true);show('loginView',false);show('appView',true);await loadMasters();await loadRegistry();$('issuedOn').value=new Date().toISOString().slice(0,10)}
async function loadMasters(){const [a,b,c]=await Promise.all([db.from('ica_issuers').select('*').eq('is_active',true).order('code'),db.from('ica_credential_types').select('*').eq('is_active',true).order('code'),db.from('ica_detail_types').select('*').eq('is_active',true).order('name_ko')]);if(a.error||b.error||c.error)throw new Error((a.error||b.error||c.error).message);issuers=a.data;types=b.data;details=c.data;$('issuer').innerHTML=issuers.map(x=>`<option value="${x.code}">${x.code} · ${x.name_ko}</option>`).join('');$('type').innerHTML=types.map(x=>`<option value="${x.code}">${x.code} · ${x.name_ko}</option>`).join('');refreshDetail();await refreshPreview()}
function refreshDetail(){const i=issuers.find(x=>x.code===$('issuer').value),t=types.find(x=>x.code===$('type').value);const rows=details.filter(x=>x.credential_type_id===t?.id&&(!x.issuer_id||x.issuer_id===i?.id));$('detail').innerHTML='<option value="">직접입력 / 선택 없음</option>'+rows.map(x=>`<option value="${x.id}">${x.name_ko}</option>`).join('');$('cardRequested').checked=!!t?.default_card;$('documentRequested').checked=!!t?.default_document}
async function refreshPreview(){refreshDetail();$('nextNo').textContent='확인 중…';const {data,error}=await db.rpc('ica_preview_credential_no',{p_issuer_code:$('issuer').value,p_type_code:$('type').value});$('nextNo').textContent=error?'발급 규칙 없음':data}
$('issuer').onchange=refreshPreview;$('type').onchange=refreshPreview;
$('issueForm').addEventListener('submit',async e=>{e.preventDefault();if(!confirm(`${val('personName')} 님의 Credential을 발급할까요?\n발급번호는 이 시점에 확정됩니다.`))return;$('issueMsg').textContent='발급 처리 중…';const payload={issuer_code:$('issuer').value,type_code:$('type').value,detail_type_id:$('detail').value||null,detail_label:val('detailLabel'),person_name:val('personName'),person_name_en:val('personNameEn'),photo_url:val('photoUrl'),qualification_name:val('qualificationName'),discipline:val('discipline'),rank_grade:val('rankGrade'),position_title:val('positionTitle'),issued_on:$('issuedOn').value,valid_until:$('validUntil').value,phone:val('phone'),email:val('personEmail'),postal_code:val('postalCode'),address:val('address'),address_detail:val('addressDetail'),admin_note:val('adminNote'),card_requested:$('cardRequested').checked,document_requested:$('documentRequested').checked};const {data,error}=await db.rpc('ica_issue_credential',{p_data:payload});if(error){$('issueMsg').textContent='발급 실패: '+error.message;return}$('issueMsg').textContent=`발급 완료 · ${data.credential_no}`;$('issueForm').reset();$('issuedOn').value=new Date().toISOString().slice(0,10);await refreshPreview();await loadRegistry();alert(`발급 완료\n${data.credential_no}`)});

async function loadRegistry(){const {data,error}=await db.from('ica_credentials').select('*,ica_issuers(code,name_ko),ica_credential_types(code,name_ko),ica_detail_types(name_ko)').order('created_at',{ascending:false});if(error){console.error(error);return}credentials=data||[];$('credentialCount').textContent=credentials.length;renderRegistry()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRegistry(){const q=val('registrySearch').toLowerCase();const rows=credentials.filter(x=>!q||x.credential_no.toLowerCase().includes(q)||x.person_name.toLowerCase().includes(q));$('registryList').innerHTML=rows.length?rows.map(x=>`<article class="item"><div><strong>${esc(x.credential_no)}</strong><small>${esc(x.ica_issuers.name_ko)} · ${esc(x.ica_credential_types.name_ko)}</small></div><div><strong>${esc(x.person_name)}</strong><small>${esc(x.rank_grade||x.position_title||x.qualification_name||'—')}</small></div><div><span class="badge ${x.status}">${x.status}</span><small>${x.issued_on}</small></div><div class="item-actions"><a href="../print/card.html?id=${x.id}" target="_blank">CARD</a><a href="../print/document.html?id=${x.id}" target="_blank">증서</a><button onclick="openShipping('${x.id}')">발송</button><button onclick="reissue('${x.id}','${esc(x.credential_no)}')">재발급</button><button class="danger" onclick="changeStatus('${x.id}','${x.status}')">상태</button></div></article>`).join(''):'<p>발급자료가 없습니다.</p>'}
$('registrySearch').oninput=renderRegistry;
async function changeStatus(id,current){const next=prompt('변경 상태를 입력하세요: VALID / EXPIRED / SUSPENDED / REVOKED',current);if(!next)return;const reason=prompt('변경 사유를 입력하세요.')||'';const {error}=await db.rpc('ica_change_status',{p_credential_id:id,p_new_status:next,p_reason:reason});if(error)return alert('상태변경 실패: '+error.message);await loadRegistry()}
async function reissue(id,no){const reason=prompt(`${no} 재발급 사유를 입력하세요.\n공식번호는 변경되지 않습니다.`);if(!reason)return;const {error}=await db.rpc('ica_record_reissue',{p_credential_id:id,p_reason:reason});if(error)return alert('재발급 기록 실패: '+error.message);alert(`${no} 재발급 기록 완료\n기존 번호가 유지됩니다.`)}
async function openShipping(id){document.querySelector('[data-tab="shipping"]').click();const c=credentials.find(x=>x.id===id);$('shippingCredentialId').value=id;$('shippingNo').value=c.credential_no;$('recipientName').value=c.person_name;$('recipientPhone').value=c.phone||'';$('shippingPostalCode').value=c.postal_code||'';$('shippingAddress').value=c.address||'';$('shippingAddressDetail').value=c.address_detail||'';const {data}=await db.from('ica_shipments').select('*').eq('credential_id',id).maybeSingle();if(data){$('shippingStatus').value=data.fulfillment_status;$('recipientName').value=data.recipient_name;$('recipientPhone').value=data.recipient_phone||'';$('shippingPostalCode').value=data.postal_code||'';$('shippingAddress').value=data.address||'';$('shippingAddressDetail').value=data.address_detail||'';$('shippingMethod').value=data.shipping_method||'';$('trackingNumber').value=data.tracking_number||'';$('shippedOn').value=data.shipped_on||'';$('shippingCost').value=data.shipping_cost??'';$('shippingNote').value=data.note||''}show('shippingForm',true)}
$('shippingForm').addEventListener('submit',async e=>{e.preventDefault();const row={credential_id:val('shippingCredentialId'),fulfillment_status:$('shippingStatus').value,recipient_name:val('recipientName'),recipient_phone:val('recipientPhone'),postal_code:val('shippingPostalCode'),address:val('shippingAddress'),address_detail:val('shippingAddressDetail'),shipping_method:val('shippingMethod'),tracking_number:val('trackingNumber'),shipped_on:$('shippedOn').value||null,shipping_cost:$('shippingCost').value?Number($('shippingCost').value):null,note:val('shippingNote'),updated_at:new Date().toISOString()};const {error}=await db.from('ica_shipments').upsert(row,{onConflict:'credential_id'});$('shippingMsg').textContent=error?'저장 실패: '+error.message:'발송정보를 저장했습니다.'});
document.querySelectorAll('.tabs [data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(`tab-${b.dataset.tab}`).classList.remove('hidden')});
window.changeStatus=changeStatus;window.reissue=reissue;window.openShipping=openShipping;

// Overseas branch photo manager — isolated extension for ICA ADMIN.
let overseasBranches=[];
function installBranchManager(){
 const nav=document.querySelector('.tabs'), shippingBtn=nav?.querySelector('[data-tab="shipping"]'), shippingTab=$('tab-shipping');
 if(!nav||!shippingBtn||!shippingTab||$('tab-branches'))return;
 const btn=document.createElement('button');btn.type='button';btn.dataset.tab='branches';btn.textContent='해외지부 관리';nav.insertBefore(btn,shippingBtn);
 const sec=document.createElement('section');sec.id='tab-branches';sec.className='tab panel hidden';sec.innerHTML=`<div class="section-head"><h2>해외지부 관리</h2><input id="branchSearch" placeholder="이름 · 국가 · 도시 · 지부번호 검색"></div><p>지부장 사진과 현재 공식 직책을 관리합니다.</p><div id="branchList" class="list"></div><form id="branchEditForm" class="grid hidden" style="margin-top:24px"><input id="branchCode" type="hidden"><label>지부장<input id="branchLeader" readonly></label><label>공식 직책<input id="branchPosition" placeholder="President"></label><label>임명일<input id="branchAppointment" type="date"></label><label>사진 선택<input id="branchPhoto" type="file" accept="image/jpeg,image/png,image/webp"></label><div class="wide" id="branchPhotoPreview"></div><div class="actions wide"><button type="submit" class="primary">사진·지부정보 저장</button><span id="branchMsg" class="msg"></span></div></form>`;shippingTab.parentNode.insertBefore(sec,shippingTab);
 btn.onclick=async()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));sec.classList.remove('hidden');await loadBranches()};
 $('branchSearch').oninput=renderBranches;
 $('branchEditForm').onsubmit=saveBranchProfile;
}
async function loadBranches(){const {data,error}=await db.from('gms_overseas_branches').select('branch_no,branch_code,country,city_or_region,branch_name,leader_name,status,leader_photo_url,leader_position,appointment_date').order('branch_no');if(error){$('branchList').innerHTML=`<p class="msg">지부 조회 실패: ${esc(error.message)}</p>`;return}overseasBranches=data||[];renderBranches()}
function renderBranches(){const q=($('branchSearch')?.value||'').trim().toLowerCase();const rows=overseasBranches.filter(x=>!q||[x.branch_no,x.branch_code,x.country,x.city_or_region,x.branch_name,x.leader_name].some(v=>String(v||'').toLowerCase().includes(q)));$('branchList').innerHTML=rows.length?rows.map(x=>`<article class="item"><div><strong>${esc(x.branch_name)}</strong><small>${esc(x.country)} · ${esc(x.city_or_region)} · #${esc(x.branch_no)}</small></div><div><strong>${esc(x.leader_name||'—')}</strong><small>${esc(x.leader_position||'—')}</small></div><div>${x.leader_photo_url?`<img src="${esc(x.leader_photo_url)}" alt="" style="width:54px;height:54px;object-fit:cover;border-radius:8px">`:'<small>사진 미등록</small>'}</div><div class="item-actions"><button type="button" onclick="editBranch('${esc(x.branch_code)}')">사진 등록/수정</button></div></article>`).join(''):'<p>검색 결과가 없습니다.</p>'}
function editBranch(code){const x=overseasBranches.find(r=>r.branch_code===code);if(!x)return;$('branchCode').value=x.branch_code;$('branchLeader').value=x.leader_name||'';$('branchPosition').value=x.leader_position||'';$('branchAppointment').value=x.appointment_date||'';$('branchPhoto').value='';$('branchPhotoPreview').innerHTML=x.leader_photo_url?`<img src="${esc(x.leader_photo_url)}" alt="${esc(x.leader_name)}" style="max-width:180px;max-height:220px;object-fit:cover;border-radius:12px">`:'';$('branchMsg').textContent='';show('branchEditForm',true);$('branchEditForm').scrollIntoView({behavior:'smooth',block:'center'})}
async function saveBranchProfile(e){e.preventDefault();const code=val('branchCode'),file=$('branchPhoto').files[0];$('branchMsg').textContent='저장 중…';let photoUrl=overseasBranches.find(x=>x.branch_code===code)?.leader_photo_url||null;if(file){if(!/^image\/(jpeg|png|webp)$/.test(file.type)){ $('branchMsg').textContent='JPG, PNG, WEBP 사진만 등록할 수 있습니다.';return }const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace('jpeg','jpg');const path=`branches/${code}/${Date.now()}.${ext}`;const up=await db.storage.from('ica-public').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(up.error){$('branchMsg').textContent='사진 업로드 실패: '+up.error.message;return}photoUrl=db.storage.from('ica-public').getPublicUrl(path).data.publicUrl}
 const {error}=await db.from('gms_overseas_branches').update({leader_photo_url:photoUrl,leader_position:val('branchPosition')||null,appointment_date:$('branchAppointment').value||null,updated_at:new Date().toISOString()}).eq('branch_code',code);if(error){$('branchMsg').textContent='지부정보 저장 실패: '+error.message;return}$('branchMsg').textContent='저장 완료';await loadBranches();editBranch(code)}
window.editBranch=editBranch;installBranchManager();
init().catch(e=>{$('loginMsg').textContent=e.message});
