const db=window.supabase.createClient(ICA_CONFIG.supabaseUrl,ICA_CONFIG.supabaseKey);
const $=id=>document.getElementById(id); let issuers=[],types=[],details=[],credentials=[];
const val=id=>$(id).value.trim(); const show=(id,on)=>$(id).classList.toggle('hidden',!on);

async function consumeGmsHandoff(){
  const raw=location.hash||'';
  const m=raw.match(/^#gms_sso=([A-Za-z0-9_-]+)$/);
  if(!m)return false;
  history.replaceState({},document.title,location.pathname+location.search);
  $('loginMsg').textContent='GMS 관리자 인증을 확인하는 중…';
  const {data,error}=await db.auth.verifyOtp({token_hash:m[1],type:'magiclink'});
  if(error||!data?.session){$('loginMsg').textContent='GMS 인증 연결이 만료되었거나 유효하지 않습니다.';return false}
  await enter(data.session);return true;
}
async function init(){
  if(await consumeGmsHandoff())return;
  const {data:{session}}=await db.auth.getSession();
  if(session) await enter(session); else show('loginView',true);
}
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('loginMsg').textContent='확인 중…';const {data,error}=await db.auth.signInWithPassword({email:val('email'),password:val('password')});if(error){$('loginMsg').textContent='로그인 실패: '+error.message;return}await enter(data.session)});
$('logoutBtn').onclick=async()=>{await db.auth.signOut();location.reload()};
async function enter(session){const {data:ctx,error}=await db.rpc('gms_get_my_admin_context');if(error||!ctx?.is_admin){await db.auth.signOut();$('loginMsg').textContent='ICA 관리자 권한이 없습니다.';show('loginView',true);return}$('adminEmail').textContent=ctx.email+' · '+ctx.role;show('logoutBtn',true);show('loginView',false);show('appView',true);await loadMasters();await loadRegistry();$('issuedOn').value=new Date().toISOString().slice(0,10)}
async function loadMasters(){const [a,b,c]=await Promise.all([db.from('ica_issuers').select('*').eq('is_active',true).order('code'),db.from('ica_credential_types').select('*').eq('is_active',true).order('code'),db.from('ica_detail_types').select('*').eq('is_active',true).order('name_ko')]);if(a.error||b.error||c.error)throw new Error((a.error||b.error||c.error).message);issuers=a.data;types=b.data;details=c.data;$('issuer').innerHTML=issuers.map(x=>`<option value="${x.code}">${x.code} · ${x.name_ko}</option>`).join('');$('type').innerHTML=types.map(x=>`<option value="${x.code}">${x.code} · ${x.name_ko}</option>`).join('');refreshDetail();await refreshPreview()}
function refreshDetail(){const i=issuers.find(x=>x.code===$('issuer').value),t=types.find(x=>x.code===$('type').value);const rows=details.filter(x=>x.credential_type_id===t?.id&&(!x.issuer_id||x.issuer_id===i?.id));$('detail').innerHTML='<option value="">직접입력 / 선택 없음</option>'+rows.map(x=>`<option value="${x.id}">${x.name_ko}</option>`).join('');$('cardRequested').checked=!!t?.default_card;$('documentRequested').checked=!!t?.default_document}
async function refreshPreview(){refreshDetail();$('nextNo').textContent='확인 중…';const {data,error}=await db.rpc('ica_preview_credential_no',{p_issuer_code:$('issuer').value,p_type_code:$('type').value});$('nextNo').textContent=error?'발급 규칙 없음':data}
$('issuer').onchange=refreshPreview;$('type').onchange=refreshPreview;
$('issueForm').addEventListener('submit',async e=>{e.preventDefault();if(!confirm(`${val('personName')} 님의 Credential을 발급할까요?\n발급번호는 이 시점에 확정됩니다.`))return;$('issueMsg').textContent='발급 처리 중…';const payload={issuer_code:$('issuer').value,type_code:$('type').value,detail_type_id:$('detail').value||null,detail_label:val('detailLabel'),person_name:val('personName'),person_name_en:val('personNameEn'),photo_url:val('photoUrl'),qualification_name:val('qualificationName'),discipline:val('discipline'),rank_grade:val('rankGrade'),position_title:val('positionTitle'),issued_on:$('issuedOn').value,valid_until:$('validUntil').value,phone:val('phone'),email:val('personEmail'),postal_code:val('postalCode'),address:val('address'),address_detail:val('addressDetail'),admin_note:val('adminNote'),card_requested:$('cardRequested').checked,document_requested:$('documentRequested').checked};const {data,error}=await db.rpc('ica_issue_credential',{p_data:payload});if(error){$('issueMsg').textContent='발급 실패: '+error.message;return}$('issueMsg').textContent=`발급 완료 · ${data.credential_no}`;$('issueForm').reset();$('issuedOn').value=new Date().toISOString().slice(0,10);await refreshPreview();await loadRegistry();alert(`발급 완료\n${data.credential_no}`)});

async function loadRegistry(){const {data,error}=await db.from('ica_credentials').select('*,ica_issuers(code,name_ko),ica_credential_types(code,name_ko),ica_detail_types(name_ko)').order('created_at',{ascending:false});if(error){console.error(error);return}credentials=data||[];$('credentialCount').textContent=credentials.length;renderRegistry()}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderRegistry(){const q=val('registrySearch').toLowerCase();const rows=credentials.filter(x=>!q||x.credential_no.toLowerCase().includes(q)||x.person_name.toLowerCase().includes(q));$('registryList').innerHTML=rows.length?rows.map(x=>`<article class="item"><div><strong>${esc(x.credential_no)}</strong><small>${esc(x.ica_issuers.name_ko)} · ${esc(x.ica_credential_types.name_ko)}</small></div><div><strong>${esc(x.person_name)}</strong><small>${esc(x.rank_grade||x.position_title||x.qualification_name||'—')}</small></div><div><span class="badge ${x.status}">${x.status}</span><small>${x.issued_on}</small></div><div class="item-actions"><a href="../print/card.html?id=${x.id}" target="_blank">CARD</a><a href="../print/document.html?id=${x.id}" target="_blank">증서</a><button onclick="openShipping('${x.id}')">발송</button><button onclick="reissue('${x.id}','${esc(x.credential_no)}')">재발급</button><button class="danger" onclick="changeStatus('${x.id}','${x.status}')">상태</button></div></article>`).join(''):'<p>발급자료가 없습니다.</p>'}
$('registrySearch').oninput=renderRegistry;
async function changeStatus(id,current){const next=prompt('변경 상태를 입력하세요: VALID / EXPIRED / SUSPENDED / REVOKED',current);if(!next)return;const reason=prompt('변경 사유를 입력하세요.')||'';const {error}=await db.rpc('ica_change_status',{p_credential_id:id,p_new_status:next,p_reason:reason});if(error)return alert('상태변경 실패: '+error.message);await loadRegistry()}
async function reissue(id,no){const reason=prompt(`${no} 재발급 사유를 입력하세요.\n공식번호는 변경되지 않습니다.`);if(!reason)return;const {error}=await db.rpc('ica_record_reissue',{p_credential_id:id,p_reason:reason});if(error)return alert('재발급 기록 실패: '+error.message);alert(`${no} 재발급 기록 완료\n기존 번호가 유지됩니다.`)}
async function openShipping(id){document.querySelector('[data-tab="shipping"]').click();const c=credentials.find(x=>x.id===id);$('shippingCredentialId').value=id;$('shippingNo').value=c.credential_no;$('recipientName').value=c.person_name;$('recipientPhone').value=c.phone||'';$('shippingPostalCode').value=c.postal_code||'';$('shippingAddress').value=c.address||'';$('shippingAddressDetail').value=c.address_detail||'';const {data}=await db.from('ica_shipments').select('*').eq('credential_id',id).maybeSingle();if(data){$('shippingStatus').value=data.fulfillment_status;$('recipientName').value=data.recipient_name;$('recipientPhone').value=data.recipient_phone||'';$('shippingPostalCode').value=data.postal_code||'';$('shippingAddress').value=data.address||'';$('shippingAddressDetail').value=data.address_detail||'';$('shippingMethod').value=data.shipping_method||'';$('trackingNumber').value=data.tracking_number||'';$('shippedOn').value=data.shipped_on||'';$('shippingCost').value=data.shipping_cost??'';$('shippingNote').value=data.note||''}show('shippingForm',true)}
$('shippingForm').addEventListener('submit',async e=>{e.preventDefault();const row={credential_id:val('shippingCredentialId'),fulfillment_status:$('shippingStatus').value,recipient_name:val('recipientName'),recipient_phone:val('recipientPhone'),postal_code:val('shippingPostalCode'),address:val('shippingAddress'),address_detail:val('shippingAddressDetail'),shipping_method:val('shippingMethod'),tracking_number:val('trackingNumber'),shipped_on:$('shippedOn').value||null,shipping_cost:$('shippingCost').value?Number($('shippingCost').value):null,note:val('shippingNote'),updated_at:new Date().toISOString()};const {error}=await db.from('ica_shipments').upsert(row,{onConflict:'credential_id'});$('shippingMsg').textContent=error?'저장 실패: '+error.message:'발송정보를 저장했습니다.'});
document.querySelectorAll('.tabs [data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(`tab-${b.dataset.tab}`).classList.remove('hidden')});
window.changeStatus=changeStatus;window.reissue=reissue;window.openShipping=openShipping;init().catch(e=>{$('loginMsg').textContent=e.message});
