-- GMS v2.1.0 : 기존 단증회원 + 공개 통계 + 실시간 활동피드
-- 1) 이 SQL을 Supabase SQL Editor에서 먼저 실행
-- 2) Table Editor > gms_legacy_members > Import data from CSV 로 legacy_members_all_977.csv 업로드
--    (또는 IPMA 720 / WTKF 257 파일을 각각 업로드)
-- 개인정보 보호: 주민등록번호는 저장하지 않으며 생년월일만 저장합니다.

create table if not exists public.gms_legacy_members (
  id bigint generated by default as identity primary key,
  organization_code text not null check (organization_code in ('WTKF','IPMA','IDP')),
  certificate_no text not null,
  name text not null,
  birth_date date,
  issued_at date,
  name_en text,
  rank_no integer,
  person_key text not null,
  linked_member_id uuid null references public.members(id) on delete set null,
  source_file text,
  import_batch text,
  status text not null default 'legacy' check (status in ('legacy','linked','inactive')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_code, certificate_no)
);

create index if not exists idx_gms_legacy_org on public.gms_legacy_members(organization_code);
create index if not exists idx_gms_legacy_person_key on public.gms_legacy_members(person_key);
create index if not exists idx_gms_legacy_name_birth on public.gms_legacy_members(name,birth_date);

alter table public.gms_legacy_members enable row level security;
drop policy if exists "gms legacy admin read" on public.gms_legacy_members;
create policy "gms legacy admin read" on public.gms_legacy_members
for select to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) in ('jeonseongkweon@gmail.com','ipma1822@gmail.com'));

-- 공개 활동은 이름을 마스킹한 값만 저장합니다.
create table if not exists public.gms_public_activity (
  id bigint generated by default as identity primary key,
  organization_code text not null check (organization_code in ('WTKF','IPMA','IDP')),
  event_type text not null check (event_type in ('new_member','new_branch','appointment','certificate','notice')),
  subject_masked text,
  detail text,
  source_table text,
  source_id text,
  is_public boolean not null default true,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create index if not exists idx_gms_public_activity_org_time on public.gms_public_activity(organization_code,occurred_at desc);
alter table public.gms_public_activity enable row level security;

drop policy if exists "gms activity admin all" on public.gms_public_activity;
create policy "gms activity admin all" on public.gms_public_activity
for all to authenticated
using (lower(coalesce(auth.jwt()->>'email','')) in ('jeonseongkweon@gmail.com','ipma1822@gmail.com'))
with check (lower(coalesce(auth.jwt()->>'email','')) in ('jeonseongkweon@gmail.com','ipma1822@gmail.com'));

create or replace function public.gms_mask_name(p_name text)
returns text language plpgsql immutable as $$
declare n text := trim(coalesce(p_name,'')); l int;
begin
  l := char_length(n);
  if l = 0 then return '회원'; end if;
  if l = 1 then return n || '*'; end if;
  if l = 2 then return substr(n,1,1) || '*'; end if;
  return substr(n,1,1) || repeat('*',greatest(l-2,1)) || substr(n,l,1);
end $$;

-- 홈페이지용 공개 통계: 개인정보는 반환하지 않습니다.
create or replace function public.gms_get_public_stats(p_organization_code text default null)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  v_org text := upper(nullif(trim(p_organization_code),''));
  v_legacy bigint := 0;
  v_unique bigint := 0;
  v_online bigint := 0;
  v_approved bigint := 0;
  v_activity30 bigint := 0;
  v_table text;
begin
  select count(*) into v_legacy from gms_legacy_members
   where status <> 'inactive' and (v_org is null or organization_code=v_org);
  select count(distinct person_key) into v_unique from gms_legacy_members where status <> 'inactive';
  select count(*) into v_online from members where coalesce(status,'active') <> 'inactive';

  if v_org='IPMA' then v_table:='ipma_member_applications';
  elsif v_org='WTKF' then v_table:='wtkf_member_applications';
  elsif v_org='IDP' then v_table:='idp_member_applications';
  end if;
  if v_table is not null and to_regclass('public.'||v_table) is not null then
    execute format('select count(*) from public.%I where lower(coalesce(status::text,''''))=''approved''',v_table) into v_approved;
  end if;

  select count(*) into v_activity30 from gms_public_activity
   where is_public=true and occurred_at >= now()-interval '30 days'
     and (v_org is null or organization_code=v_org);

  return jsonb_build_object(
    'organization_code',v_org,
    'legacy_members',v_legacy,
    'legacy_unique_people',v_unique,
    'online_members_total',v_online,
    'approved_applications',v_approved,
    'activity_30d',v_activity30
  );
end $$;

revoke all on function public.gms_get_public_stats(text) from public;
grant execute on function public.gms_get_public_stats(text) to anon, authenticated;

create or replace function public.gms_get_public_activity(p_organization_code text default null, p_limit integer default 12)
returns table(id bigint,organization_code text,event_type text,subject_masked text,detail text,occurred_at timestamptz)
language sql
security definer
set search_path=public
as $$
  select a.id,a.organization_code,a.event_type,a.subject_masked,a.detail,a.occurred_at
  from gms_public_activity a
  where a.is_public=true
    and (nullif(upper(trim(p_organization_code)),'') is null or a.organization_code=upper(trim(p_organization_code)))
  order by a.occurred_at desc
  limit greatest(1,least(coalesce(p_limit,12),50));
$$;
revoke all on function public.gms_get_public_activity(text,integer) from public;
grant execute on function public.gms_get_public_activity(text,integer) to anon, authenticated;

-- 관리자 수동 게시: 임원 임명 / 지부 등록 / 공지 등에 사용
create or replace function public.gms_publish_activity(p_organization_code text,p_event_type text,p_name text default null,p_detail text default null)
returns bigint
language plpgsql
security definer
set search_path=public
as $$
declare v_id bigint; v_email text:=lower(coalesce(auth.jwt()->>'email',''));
begin
  if v_email not in ('jeonseongkweon@gmail.com','ipma1822@gmail.com') then raise exception 'admin only'; end if;
  insert into gms_public_activity(organization_code,event_type,subject_masked,detail)
  values(upper(p_organization_code),p_event_type,gms_mask_name(p_name),p_detail)
  returning id into v_id;
  return v_id;
end $$;
grant execute on function public.gms_publish_activity(text,text,text,text) to authenticated;

-- 회원가입 신청이 'approved'로 바뀌는 순간 자동 공개피드 생성
create or replace function public.gms_feed_from_application()
returns trigger language plpgsql security definer set search_path=public as $$
declare j jsonb:=to_jsonb(new); oldj jsonb:=case when tg_op='UPDATE' then to_jsonb(old) else '{}'::jsonb end;
        v_status text:=lower(coalesce(j->>'status',''));
        v_old_status text:=lower(coalesce(oldj->>'status',''));
        v_org text; v_name text; v_type text:='new_member'; v_detail text;
begin
  if v_status <> 'approved' or v_old_status='approved' then return new; end if;
  if tg_table_name='ipma_member_applications' then v_org:='IPMA';
  elsif tg_table_name='wtkf_member_applications' then v_org:='WTKF';
  elsif tg_table_name='idp_member_applications' then v_org:='IDP';
  elsif tg_table_name='idp_branch_applications' then v_org:='IDP'; v_type:='new_branch';
  else return new; end if;
  v_name:=coalesce(j->>'name',j->>'applicant_name',j->>'branch_name',j->>'representative_name');
  if v_type='new_member' then v_detail:='신규 회원이 등록되었습니다.'; else v_detail:='신규 지부가 등록되었습니다.'; end if;
  insert into gms_public_activity(organization_code,event_type,subject_masked,detail,source_table,source_id)
  values(v_org,v_type,gms_mask_name(v_name),v_detail,tg_table_name,coalesce(j->>'id',''));
  return new;
end $$;

-- 존재하는 테이블에만 트리거 생성
DO $$
declare t text; trg text;
begin
  foreach t in array array['ipma_member_applications','wtkf_member_applications','idp_member_applications','idp_branch_applications'] loop
    if to_regclass('public.'||t) is not null then
      trg:='trg_gms_feed_'||t;
      execute format('drop trigger if exists %I on public.%I',trg,t);
      execute format('create trigger %I after insert or update of status on public.%I for each row execute function public.gms_feed_from_application()',trg,t);
    end if;
  end loop;
end $$;

-- 설치 확인용
select public.gms_get_public_stats(null) as gms_stats_after_setup;
